### ISSUE TITLE
Compatibility with GHC 7.10

### ISSUE THREAD

**Issue by eggzilla** [ivan-m/graphviz#1]
Hi I wanted to bring to your attention, that there are two reported issues regarding the compatibility of this package with GHC 7.10 in the old darcs issue tracker.

http://hub.darcs.net/ivanm/graphviz/issue/9
http://hub.darcs.net/ivanm/graphviz/issue/5

Would be really nice if you could include these changes, or comment on them :-)
Thanks

**Comment by ivan-m** [comment]
Yes, I know... I'm trying to get FGL up to scratch first (I'm still in the process of migrating graphviz over to here).
