### ISSUE TITLE
Provide a GraphvizParams with sufficiently smart defaults

### ISSUE THREAD

**Issue by seagreen** [ivan-m/graphviz#11]
I think this is just a documentation issue, but it's hard to figure out what the last item in the tuples passed to `graphInDotFormat` are meant to be used for. In my exploration of the types it appears they're related to labeling vertices/edges, but changing them isn't affecting the generated `.dot` file at all.

Haskell code:
```haskell
foo :: IO ()
foo = do
    let graphInDotFormat = graphElemsToDot nonClusteredParams vertices edges
        outputText = renderDot $ toDot graphInDotFormat
    liftIO $ TIO.writeFile "graph.dot" (TL.toStrict outputText)
  where
    vertices :: [(Int,String)]
    vertices = [(1,"foo"),(2, "bar")]

    edges :: [(Int,Int,String)]
    edges = [(1,2,"baz")]
```

Output:
```
digraph {
    1;
    2;
    1 -> 2;
}
```

My goal is to take a list of (uniqueIds, labels) and output it as `.dot` nodes, and another list of (uniqueIds, uniqueIds) and output it as `.dot` edges. Is there a place in the docs that talks about how to do this?

**Comment by ivan-m** [comment]
You need to set the `GraphvizParams` value to actually do something with your labels (the `Strings` you have) to know what to do with them.

```haskell
λ> let nodeFmt (_,l) = [toLabel l]
λ> let edgeFmt (_,_,l) = [toLabel l]
λ> let params = nonClusteredParams { fmtNode = nodeFmt, fmtEdge = edgeFmt }
λ> putDot (graphElemsToDot params [(1,"foo"), (2,"bar")] [(1,2,"baz")])
digraph {
    1 [label=foo];
    2 [label=bar];
    1 -> 2 [label=baz];
}
```

This is documented at the top of the `Specifying parameters.` section of the Haddock docs.

**Comment by seagreen** [comment]
Thanks, that worked great. From a beginners perspective it would be helpful to have that be the default for `defaultParams`, but I there may be good reasons not to do so.

**Comment by ivan-m** [comment]
Well, if that was the default, it would place extra constraints on the types allowed for the labels... which you don't want to always do.

What _might_ be more useful is to have a variant with these defined for people.

**Comment by seagreen** [comment]
Good point. Not having the type constraints actually adds a little confusion when first exploring the library though -- I knew the last item in the tuples was label related, so it was strange I could put types without `Show` there.

So I think people that already have their own graph types will appreciate the current `GraphvizParams` values provided, but for someone who's like "I have an `[(Int, String)]` and an `[(Int, Int, String)]`, I wonder if I can make a graph in a one liner?" new ones might be useful.
