### ISSUE TITLE
[question] Version numbering scheme

### ISSUE THREAD

**Issue by ocramz** [ivan-m/graphviz#12]
What's wrong with version numbering? Is it supposed to be a joke, or some sort of pun?

**Comment by ivan-m** [comment]
Come again? There is version numbering present.

**Comment by ocramz** [comment]
I was wondering about the `2999.x.y.z` format, which as far as I can see is quite unique.

**Comment by ivan-m** [comment]
[See the FAQ](https://github.com/ivan-m/graphviz/blob/master/FAQ.md#why-are-the-version-numbers-so-high).

**Comment by ivan-m** [comment]
Note also that this [isn't unique](https://hackage.haskell.org/package/HTTP).

**Comment by ocramz** [comment]
Thank you for the pointers, but I still don't see any rationale to it. I don't particularly care about any formal PVP, but version numbers entries are usually small integers.

**Comment by ivan-m** [comment]
Look at the version numbers for [older versions](http://hackage.haskell.org/package/graphviz).

If I wanted a newer version, it had to have the first component be >= 2009 if I wanted it to appear as being newer than the older versions.

I'm not sure if there's any other explanation that I can provide that works.  I suppose I could change to `3000.x` now but that won't happen if/until I do a re-write.

(And if you care about semantic versioning and being able to more sanely determine the likelihood of backwards compatibility of package dependencies, then you *should* care about the PVP.)
