### ISSUE TITLE
Escaping curly braces, vertical bars, and angle brackets in record-based nodes

### ISSUE THREAD

**Issue by marc-reh** [ivan-m/graphviz#15]
I would like to suggest the addition of curly braces, vertical bars and angle brackets to the definition of escape letters (letters for which a preceding slash is not escaped).

In Printing.hs:

escLetters = Set.fromList ['N', 'G', 'E', 'T', 'H', 'L', 'n', 'l', 'r','{','}','|','<','>']

See also http://www.graphviz.org/doc/info/shapes.html#record

**Comment by ivan-m** [comment]
Except there is explicit support for [record labels](http://hackage.haskell.org/package/graphviz-2999.18.1.2/docs/Data-GraphViz-Attributes-Complete.html#t:Label) already.

This escape list is used _everywhere_ for the definition of strings (e.g. identifiers), not just for labels, so it can't be used like that.

**Comment by marc-reh** [comment]
I wasn't aware of the explicit support for record labels. Using them, I don't need to escape curly braces etc. anymore and can use graphviz as is. Thanks!
