### ISSUE TITLE
lack of quoting on edge label leads to graphviz syntax error

### ISSUE THREAD

**Issue by joeyh** [ivan-m/graphviz#16]
Using the Monadic interface, I built a graph with an edge labeled "08e10". This resulted in:

    Error running utility program: Error messages from dot:
    Warning: syntax ambiguity - badly delimited number '08e' in line 1 of /home/joey/tmp/graphviz1804289383846930886.gv splits into two tokens
    Error: /home/joey/tmp/graphviz1804289383846930886.gv: syntax error in line 1 near ']'

Stracing the program (probably a better way?) to see the generated graphviz file, this is the problem edge:

SHA25608e1022b3da692ff2fbd8615da6dfba8be3b2a123270dd1e854987f9108aa07f -> SHA256984088083de532f7d0d602fa3e9c66d6380cc68ec364b8e7fa50b9b80f7f501d [color=green,label=08e10]

The label needs to be quoted to prevent graphviz from trying to parse it as a number.

I worked around this by changing the label to "hash: 08e10", which then gets quoted in the generated file.

Using graphviz 2.38.0 and version 2999.18.1.2 of this library.

**Comment by ivan-m** [comment]
Huh... I will have to have a look at this.

When printing numbers, they are deemed to be [a type of string](http://graphviz.org/doc/info/lang.html) and thus don't need to be quoted.

Any chance of getting the code you used for this as a test case?

What happens if you use a label of just `8e10` (i.e. no leading `0`)?

**Comment by joeyh** [comment]
Well, "08e10" is formatted like a number in scientific notation, but it's a Text, so it should not be interpreted that way. In fact, it was the first 5 letters of a hash..

Here's a minimal test case:

{-# LANGUAGE OverloadedStrings, FlexibleContexts #-}

import Data.GraphViz
import Data.GraphViz.Types.Generalised as G
import Data.GraphViz.Types.Monadic
import qualified Data.Text.Lazy as T

main :: IO ()
main = do
        let g = genGraph
        f <- createImage "oops.png" Png g
        print f

createImage :: PrintDotRepr dg n => FilePath -> GraphvizOutput -> dg n -> IO FilePath
createImage f o g = Data.GraphViz.addExtension (runGraphvizCommand Dot g) o f

genGraph :: G.DotGraph T.Text
genGraph = digraph (Str "oops") $ do
        node "a"
                [ textLabel "a"
                , shape BoxShape
                ]
        node "b"
                [ textLabel "b"
                , shape BoxShape
                ]
        edge ("a" :: T.Text) ("b" :: T.Text)
                [ textLabel "08e10" ]

**Comment by ivan-m** [comment]
OK, specifically it's the case that quote-less strings are numbers _without_ exponents, so it shouldn't apply here.  I'll fix this up.

(As an aside: if you're using `addExtension`, you probably don't want the `.png` in your filename.)
