### ISSUE TITLE
Simple subgraph missing

### ISSUE THREAD

**Issue by perglr** [ivan-m/graphviz#22]
`'{' stmt_list '}'`

Needed e.g. to properly render 
``` dot
digraph {
    fakeAB [label="", shape=point, width=0.01, height=0.01];
    fakeAC [label="", shape=point, width=0.01, height=0.01];

    {
        rank=same;
            "b"; "c";
    }

    {
        rank=same;
            fakeAB; fakeAC;
    }

    "a" -> fakeAB [arrowhead=none];
    "a" -> fakeAC [arrowhead=none];
    fakeAB -> "b";
    fakeAC -> "c";

    fakeAB -> fakeAC [label="b", color="red", arrowhead=none];
}
```
https://stackoverflow.com/questions/26845540/connect-edges-with-graph-dot/29752263#29752263

**Comment by ivan-m** [comment]
I'm not sure I understand what you're saying: do you mean this can't be parsed? Or that there's no way to represent this in Haskell using this library?

For the latter, create a [sub-graph](http://hackage.haskell.org/package/graphviz-2999.19.0.0/docs/src/Data-GraphViz-Types-Generalised.html#DotSubGraph) that isn't a cluster and doesn't have an ID.

**Comment by perglr** [comment]
Sorry for the vagueness, Ivan. The second one: representing this using the library, specifically using the monadic interface.

**Comment by ivan-m** [comment]
Right, I never added that in for monadic graphs thinking it wasn't that useful. You're not the first one to ask for it though so I'll do so.

**Comment by perglr** [comment]
Thank you very much, Ivan, will be looking forward, kind of stuck here now in my project ;-)
