### ISSUE TITLE
Old versions of graphviz have no constraint on fgl

### ISSUE THREAD

**Issue by ilovezfs** [ivan-m/graphviz#27]
Cross posting from https://github.com/haskell-infra/hackage-trustees/issues/114

Old versions of graphviz have no constraint on fgl. It looks like this affects everything `<=graphviz-2999.9.0.0`.

But even the latest version of graphviz (currently 2999.19.0.0) must constrain `fgl < 5.6`.

This can cause installs involving both graphviz and fgl to attempt to use one of the old graphviz versions to get around the fgl constraint if solver happens to choose `fgl >= 5.6`.

A solution to https://github.com/ivan-m/graphviz/issues/26 will also work around this, but those old graphviz versions are still landmines.

**Comment by ivan-m** [comment]
Old versions have been deprecated.
