### ISSUE TITLE
mkGraph with runGraphvizCommand produces wrong-direction arcs

### ISSUE THREAD

**Issue by jchia** [ivan-m/graphviz#28]
Sample code:
https://gist.github.com/jchia/c4a19f2a862d8476cc0b9cd024b383f6

The .dot file output resulting from using `mkGraph` & `runGraphvizCommand` has arcs that all have the wrong direction. The documentation of `DotEdge` should be changed to reflect the correct direction, or I think more appropriately, the part that generates the .dot needs to be fixed.

**Comment by ivan-m** [comment]
The problem is definitely with `mkGraph`:

```haskell
λ> import qualified Data.GraphViz.Types.Graph as GV
λ> GV.mkGraph [GV.DotNode (0 :: Int) [], GV.DotNode 1 []] [GV.DotEdge 0 1 []]
fromCanonical DotGraph {strictGraph = False, directedGraph = True, graphID = Nothing, graphStatements = DotStmts {attrStmts = [], subGraphs = [], nodeStmts = [DotNode {nodeID = 0, nodeAttributes = []},DotNode {nodeID = 1, nodeAttributes = []}], edgeStmts = [DotEdge {fromNode = 1, toNode = 0, edgeAttributes = []}]}}
```

**Comment by ivan-m** [comment]
Actually, that isn't right; the internal `DotGraph` contains the edge in both directions, but the `toCanonical` function is picking which edges to keep.

I believe this is because of the graph-based implementation was designed around undirected graphs.

**Comment by ivan-m** [comment]
The problem is with the `addPS` function; I just need to make sure that whatever changes I make still work with `(&)`.
