### ISSUE TITLE
RGB colors for a node

### ISSUE THREAD

**Issue by archaeron** [ivan-m/graphviz#40]
Hello

Thanks for this library!

I wanted to use a custom RGB color for a node. The functions to add a background color all need something with a `NamedColor` constraint (e.g. `bgColor :: NamedColor nc => nc -> Attribute`)

So I thought I'd do something like:

```
data RGB = RGB
    { red :: Word8
    , green :: Word8
    , blue :: Word8
    }

instance GV.Attributes.Colors.NamedColor RGB where
    toColor (RGB r g b) = GV.Attributes.Colors.RGB r g b
```

but then I get a warning that I'm not implementing some of the functions in `NamedColor`. but those functions are not exported.

Am I missing something?

**Comment by ivan-m** [comment]
Hi @archaeron, any particular reason for not using the `RGB` constructor of the `Color` type? (Combine with `toWC`.)  You can find them defined in Data.GraphViz.Attributes.Colors`.

**Comment by archaeron** [comment]
I am using the RGB constructor (see `toColor (RGB r g b) = GV.Attributes.Colors.RGB r g b`). But `Color` doesn't have a `NamedColor` instance, so I can't use it in the `color-` functions (like: `bgColor`) without giving it one. Is there another way to add colors to something?

**Comment by ivan-m** [comment]
You can always use the underlying Data.GraphViz.Attributes.Complete
functions directly; bgColor, etc. just provide convenience functions for
the common cases.


On mobile; please excuse any tpyos.

**Comment by archaeron** [comment]
This did the trick :) I didn't look at `Data.GraphViz.Attributes.Complete`.
Thank you!
