### ISSUE TITLE
Remove or bump upper bound on polyparse

### ISSUE THREAD

**Issue by recursion-ninja** [ivan-m/graphviz#47]
I cannot build `graphviz` (or our project which depends on `graphviz`) with `ghc-8.8.1` due to the upper bound for `polyparse` preventing `cabal` or `stack` from finding a build plan that uses the new, `ghc-8.8.1` compatible `polyparse-1.13` version of the dependent library.

**Comment by georgefst** [comment]
Please @ivan-m? This is currently the one remaining package forcing me to use `--allow-newer` on `ghc-8.8.1`.

Otherwise this might be one for the Hackage trustees before long.
