### ISSUE TITLE
are cluster edges supported?

### ISSUE THREAD

**Issue by haroldcarr** [ivan-m/graphviz#5]
Is this supported:  http://www.graphviz.org/content/FaqClusterEdge

If yes, could you provide a haskell graphviz version of the example in that link?

**Comment by ivan-m** [comment]
You should be able to convert that directly into the equivalent Haskell representation; for example (but completely untested):

```haskell
digraph (Str "G") $ do
  graphAttrs [Compound True, NodeSep 1.0]
  cluster (Str "A") $ do
    'a' --> 'b'
    'a' --> 'c'
  cluster (Str "B") $ do
    'd' --> 'e'
    'f' --> 'e'
  edge 'a' 'e' [LTail "cluster_A", LHead "cluster_B"]
```

**Comment by haroldcarr** [comment]
That works.  Thanks - I had tried close to that, but missed the "magic" of prepending "cluster_*" to the (Str "*") name.

**Comment by ivan-m** [comment]
Yeah, I might work out a cleaner way of writing that.
