### ISSUE TITLE
Documentation not building on Hackage

### ISSUE THREAD

**Issue by seagreen** [ivan-m/graphviz#9]
Not a problem for me, but I thought you might want to know (version `2999.18.1.1`).

**Comment by ivan-m** [comment]
Thanks for letting me know; I'm going to guess that this is a problem with Hackage.

In this case though I'm not too worried as the only change is is a QuickCheck version bump, so 2999.18.1.0's docs should suffice.

**Comment by ivan-m** [comment]
Specifically, this seems to be from haskell/hackage-server#478

**Comment by seagreen** [comment]
:+1:
